name: Trigger auto deployment for container-app-bn5sbrscgxxfa

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-bn5sbrscgxxfa-AutoDeployTrigger-108601b6-a46d-43d9-92e6-555830d2c12f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPBN5SBRSCGXXFA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPBN5SBRSCGXXFA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPBN5SBRSCGXXFA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPBN5SBRSCGXXFA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPBN5SBRSCGXXFA_REGISTRY_PASSWORD }}
          containerAppName: container-app-bn5sbrscgxxfa
          resourceGroup: appspacesragappdemoaf7c
          imageToBuild: default/container-app-bn5sbrscgxxfa:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


